# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Yarb Scrape

# on:
#   schedule:
#     - cron: "0 2 * * *"

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Run Scraper
      run: |
        python yarb-scrape.py

    # Runs a set of commands using the runners shell
    - name: push to origin master
      run: |
        echo start push
        git config --global user.name "0xlino"
        git config --global user.email "hello@benline.co.uk"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push