name: Daily Web3 Scraper

# on:
#   schedule:
#     - cron: "0 6 * * *"

on:
  schedule:
    - cron: "0 2 * * *"
  # push:
  #   branches:
  #     - main
  #     - 'releases/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clone pythonmodules repository
      run: |
        git clone --depth=1 https://${{ secrets.CUSTOM_TOKEN }}@github.com/0xlino/pythonmodules pythonmodules
        cd pythonmodules
        python setup.py install

    # - name: Log Directory structure
    #   run: |
    #     ls -R

    # - name: Run Scraper
    #   run: |
    #     python test.py

    - name: Run Scraper
      run: |
        python yarb-scrape.py

    # Runs a set of commands using the runners shell
    - name: push to origin master
      run: |
        echo start push
        git config --global user.name "0xlino"
        git config --global user.email "hello@benline.co.uk"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push